### ISSUE TITLE
[question] 3通貨裁定取引において各板取引量累積和について疑問

### ISSUE THREAD

**Issue by octaltree** [algori11/arbitrage_crypto#6]
実行していないので誤解かもしれません.

tri_arb.pyの関数root_uに
```
    amount1 = np.cumsum(ask1[:, 1] * ask2[-1][0])
    amount2 = np.cumsum(ask2[:, 1])
    amount3 = np.cumsum(bid3[:, 1])

    ratio = bid3[:, 0][idx[2]]/(ask1[:, 0][idx[0]]* ask2[:, 0][idx[1]])
    if ratio < threshold:
        return 0, 0
    value = np.min([amount1[idx[0]], amount2[idx[1]], amount3[idx[2]]])
```
がありますが, 取引量ask1[:, 1]に値段ask2[-1][0]をかけているように見えるのですが,
なにを意味しているんでしょうか?

**Comment by algori11** [comment]
ask1はBASE1でBASE2を買うときの板で、量がBASE2単位になっています。
ALTコイン換算で見たときの量を計算するため、とりあえずBASE2→ALT交換比率としてask2の板の情報（悪条件の場合のもの）を使っています。

**Comment by octaltree** [comment]
言われてみればたしかに値段情報がないと量がわかりませんね.
ロジック参考にさせていただいていますありがとうございます.

**Comment by octaltree** [comment]
何度もすみません. コードに間違いがあると思い書きました.
間違っている箇所あったら指摘してください.

```
PAIR1 = BASE2 + "/" + BASE1
PAIR2 = ALT + "/" + BASE2
PAIR3 = ALT + "/" + BASE1
```
より,
- ask1[:, 1]およびbid1[:, 1]はBASE2の枚数
- ask2[:, 1]およびbid2[:, 1]はALTの枚数
- ask3[:, 1]およびbid3[:, 1]はALTの枚数
- ask1[:, 0]およびbid1[:, 0]はBASE2 1枚あたりのBASE1の枚数
- ask2[:, 0]およびbid2[:, 0]はALT 1枚あたりのBASE2の枚数
- (1/ask2[-1][0])および(1/bid2[-1][0])はBASE2 1枚あたりのALTの枚数
である.

```
def root_u(ask1, ask2, bid3, threshold): 
    idx = np.zeros(3).astype(int)

    amount1 = np.cumsum(ask1[:, 1] * ask2[-1][0])
    amount2 = np.cumsum(ask2[:, 1])
    amount3 = np.cumsum(bid3[:, 1])
```
```
def root_d(bid1, bid2, ask3, threshold): 
    idx = np.zeros(3).astype(int)

    amount1 = np.cumsum(bid1[:, 1] * bid2[-1][0])
    amount2 = np.cumsum(bid2[:, 1])
    amount3 = np.cumsum(ask3[:, 1])
```
において, amount2やamount3にあわせてask1[:, 1]やbid[:, 1]の累積和をALTの枚数にしなければならない.
したがって, amount1 = np.cumsum(ask1[:, 1] * (1/ask2[-1][0])), amount1 = np.cumsum(bid1[:, 1] * (1/bid2[-1][0]))である.

になりませんか?

**Comment by algori11** [comment]
ALT一枚あたりのBASE2の枚数 * BASE2の枚数　でALTの枚数になりませんか？　次元が(ALT/BASE2) * BASE2 = ALT なので
たぶんあってると思います

**Comment by octaltree** [comment]
BASE2/BASE1
BNB/BTC
Price(BTC) 	Amount(BNB) 	Total(BTC)
0.0015286 	133.75 	0.20445025

ALT/BASE2
LTC/BNB
Price(BNB) 	Amount(LTC) 	Total(BNB)
12.57 	2.73108 	34.3296756

BNB1枚=BTC0.0015286枚でBNB133.75枚売りに出されている.
LTC1枚=BNB12.57枚でLTC2.73108枚売りに出されている.

BNB133.75枚はLTC133.75 / 12.57枚ではないでしょうか?
133.75 * 12.57枚でなく.

**Comment by algori11** [comment]
その通りでした。修正しておきます。失礼しました。
