### ISSUE TITLE
[question] 3通貨裁定取引におけるパラメータ

### ISSUE THREAD

**Issue by octaltree** [algori11/arbitrage_crypto#7]
たびたびすみません.
板の取引量を換算する場面ではask2[-1]とaskの10番目を用いるのに対して,
最小単位を求める場面ではask2[0][0]の1.1倍を使用しています.
```
    limit0 = max(limit1*ask2[0][0]*1.1, limit2, limit3)
```

取引は板にある価格や量の範囲でしか行われないんですよね?
ask2[-1][0]ではまずいのでしょうか?
パラメータ1.1は経験によるものですか?

(arb.pyでは価格にask[0][0]の1.01を使用しているようですが)

**Comment by octaltree** [comment]
#6 の話題ですがこちらもlimit1はBASE2の枚数でask2[0][0]がALT1枚あたりのBASE2の枚数だから
ALT枚数に換算すると1.1 * limit1 / ask2[0][0]とはなりませんか

**Comment by algori11** [comment]
1.1は経験で適当に書いたものです。ask2[-1][0]で問題ないと思います。
ただ、三通貨アービトラージは実質的にはほとんど板の真上付近のものしか扱わないので、実質的にはあまり変わらないものかとは思います。

**Comment by octaltree** [comment]
そんなに気にしなくても大丈夫そうな感じなので気にしなくて大丈夫ですね.
ちゃんとやるなら指値の価格で量を換算になるんですかね.
解決しましたありがとうございます.
